[package]
name = "wave-api"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
rocket = { version = "0.5.1", features = ["secrets", "json"] }
serde = "1.0.217"

[dependencies.mongodb]
version = "3.2.0"
features = ["sync"]
